import { ReactNode } from 'react'

import Providers from './providers'

import './globals.css'
import { NavigationBar } from '@components/navigation-bar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavigationBar />

          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
