export const PROFILE = 'profile'
export const REFRESH = 'refresh'
export const TOP_GENRES = 'top/genres'
export const TOP_ARTISTS = 'top/artists'
export const TOP_TRACKS = 'top/tracks'
export const RECENTLY_PLAYED = 'recently-played'
export const PLAYBACK_STATE = 'playback-state'
export const ANALYSIS = 'analysis'
