import { ReactNode } from 'react'
import { cookies } from 'next/headers'

import Providers from './providers'

import './globals.css'

import { NavigationBar } from '@components/navigation'
import { getProfile } from '@api/fetchers'
import { ACCESS_TOKEN } from '@api/constants'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export interface LayoutProps {
  children: ReactNode
}

export default async function RootLayout({ children }: LayoutProps) {
  const accessToken = cookies().get(ACCESS_TOKEN)?.value

  const profile = await getProfile(accessToken).catch(() => undefined)

  return (
    <html lang="en">
      <body className="bg-background text-white min-h-screen">
        <Providers>
          <NavigationBar profile={profile} />

          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
