export const TIME_RANGE = 'time-range'
export const VIEW = 'view'
export const STATS_PROVIDER = 'stats-provider'
export const STATS_MEASUREMENT = 'stats-measurement'
export const HIGHLIGHTED_TRACK_ID = 'highlighted-track-id'
